from datetime import datetime


def generate_report(data: str) -> str:
    """Wraps analysis output into a structured markdown report."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    return f"""# AI Analysis Report
*Generated: {timestamp}*

---

## Executive Summary

{data[:500]}{'...' if len(data) > 500 else ''}

---

## Detailed Analysis

{data}

---

## Report Metadata
- Generated by: Yuno AI Agent Platform
- Runtime: LangGraph multi-agent workflow
- Status: Completed
"""